baseURL = "https://troypeiler.com/"
languageCode = "en-us"
title = "Troy Peiler"
theme = "PaperMod"

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  disableSpecial1stPost = true
  profileModeAvatar = "circle"

[params.profileMode]
  enabled = true
  title = "Nice to meet you! I’m Troy Peiler, a compliance analyst building toward cloud security engineering."
  subtitle = "My goal is to build secure, scalable cloud systems by applying security controls thoughtfully and intentionally, not just checking boxes."
  imageUrl = "/img/profile.jpg"
  imageTitle = "Troy Peiler"
  imageWidth = 160
  imageHeight = 160
  
[[params.profileMode.buttons]]
  name = "Projects"
  url = "/projects/"

[[params.profileMode.buttons]]
  name = "Resume"
  url = "/resume/"

[[params.profileMode.buttons]]
  name = "Contact"
  url = "/contact/"

[params.label]
  icon = "🏠"
  iconHeight = 22

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/YOUR-LINK/"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/tpeiler"

[[params.socialIcons]]
  name = "email"
  url = "mailto:troy.m.peiler@gmail.com"




[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 20

  [[menu.main]]
    name = "Resume"
    url = "/resume/resume.pdf"
    weight = 3

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 40
