baseURL = "https://troypeiler.com/"
languageCode = "en-us"
title = "Troy Peiler"
theme = "PaperMod"

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  disableSpecial1stPost = true
  profileModeAvatar = "circle"

[params.profileMode]
  enabled = true
  title = "Troy Peiler"
  subtitle = "See what I’m building. Let’s learn and collaborate."
  imageUrl = "/img/profile.jpg"
  imageTitle = "Troy Peiler"
  imageWidth = 160
  imageHeight = 160
  
[[params.profileMode.buttons]]
  name = "Projects"
  url = "/projects/"

[[params.profileMode.buttons]]
  name = "Resume"
  url = "/resume/"

[[params.profileMode.buttons]]
  name = "Contact"
  url = "/contact/"

[params.label]
  icon = "🏠"
  iconHeight = 22


[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 20

  [[menu.main]]
    name = "Resume"
    url = "/resume/resume.pdf"
    weight = 3

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 40
